-- automatically generated by BNF Converter
module Main where


import System.IO ( stdin, hGetContents )
import System.Environment ( getArgs, getProgName )
import System.Exit ( exitFailure, exitSuccess )

import LexWhile
import ParWhile
import PrintWhile
import AbsWhile
import LayoutWhile
import Desugar(desugar)
import ProgToData(progToData)

import ErrM

type ParseFun a = [Token] -> Err a

myLLexer = resolveLayout True . myLexer

type Verbosity = Int

putStrV :: Verbosity -> String -> IO ()
putStrV v s = if v > 1 then putStrLn s else return ()

runFile disp v p f = -- putStrLn f >>
  readFile f >>= run disp v p

run disp v p s = let ts = myLLexer s in case p ts of
           Bad s    -> do putStrLn "\nParse              Failed...\n"
                          putStrV v "Tokens:"
                          putStrV v $ show ts
                          putStrLn s
                          exitFailure
           Ok  tree -> do -- putStrLn "\nParse Successful!"
                          -- showTree v tree
                          putStrV v $ disp tree

                          exitSuccess

-- 脱糖してコア WHILE を印字する (既定)
dispCore :: Program -> String
dispCore = printTree . desugar

-- 脱糖して programs-as-data 表現 ⌜p⌝ を印字する (p.49)
dispData :: Program -> String
dispData = printTree . progToData . desugar

showTree :: (Show a, Print a) => Int -> a -> IO ()
showTree v tree
 = do
      putStrV v $ "\n[Abstract Syntax]\n\n" ++ show tree
      putStrV v $ "\n[Linearized tree]\n\n" ++ printTree tree

usage :: IO ()
usage = do
  putStrLn $ unlines
    [ "usage: Call with one of the following argument combinations:"
    , "  --help          Display this help message."
    , "  (no arguments)  Parse stdin verbosely."
    , "  (files)         Parse content of files verbosely."
    , "  -s (files)      Silent mode. Parse content of files silently."
    , "  --data (files)  Print the programs-as-data representation (p.49)."
    ]
  exitFailure

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> usage
    [] -> hGetContents stdin >>= run dispCore 2 pProgram
    "-s":fs -> mapM_ (runFile dispCore 0 pProgram) fs
    "--data":fs -> mapM_ (runFile dispData 2 pProgram) fs
    fs -> mapM_ (runFile dispCore 2 pProgram) fs
